#######
# Compiled from /tpairmill/functions/load.mcscript
# to .//tpairmill/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function tpairmill:mcscript/load

scoreboard objectives add tpMillY dummy