#######
# Compiled from .//functions/main.mcscript
# to .//functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpAirMill] at @s if block ~ ~ ~ air run tag @s remove tpCableConnector
execute as @e[tag=tpAirMill] at @s if block ~ ~ ~ air as @e[tag=tpCable,distance=..1.1] at @s run function tpcables:update
execute as @e[tag=tpAirMill] at @s if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:3390006,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Wind Turbine\",\"italic\":false,\"color\":\"green\"}"},Fireworks:{}}}}
execute as @e[tag=tpAirMill] at @s if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:light_gray_stained_glass"}}]
execute as @e[tag=tpAirMill] at @s if block ~ ~ ~ air run kill @e[tag=tpMillBlade,distance=..0.8]
execute as @e[tag=tpAirMill] at @s if block ~ ~ ~ air run kill @s
execute as @e[tag=tpAirMill] at @s run scoreboard players add @s tpTimer 1
execute as @e[tag=tpAirMill] at @s run scoreboard players add #t2 tpTimer 1
execute as @e[tag=tpAirMill] at @s run function tpairmill:powered
execute as @e[tag=tpAirMill] at @s run function tpairmill:millmain
execute as @e[tag=tpAirMill] at @s if score #t2 tpTimer matches 300.. store result score @s tpDrillTempX run data get entity @s Pos[1]
execute as @e[tag=tpAirMill] at @s if score #t2 tpTimer matches 300.. run scoreboard players set @s tpMillY -1
execute as @e[tag=tpAirMill] at @s if score #t2 tpTimer matches 300.. unless entity @s[y=60,dy=-60] run function tpairmill:rayl
execute as @e[tag=tpAirMill] at @s if score #t2 tpTimer matches 300.. run scoreboard players set @s tpDrillTempX 10
execute as @e[tag=tpAirMill] at @s if score #t2 tpTimer matches 300.. run scoreboard players operation @s tpMillY *= @s tpDrillTempX
execute as @e[tag=tpAirMill] at @s if score #t2 tpTimer matches 300.. run scoreboard players set @s tpDrillTempX 15
execute as @e[tag=tpAirMill] at @s if score #t2 tpTimer matches 300.. run scoreboard players operation @s tpMillY /= @s tpDrillTempX
execute as @e[tag=tpAirMill] at @s if score #t2 tpTimer matches 300.. positioned ~ ~-0.67 ~ run scoreboard players operation @e[tag=tpMillBlade,distance=..0.4] tpMillY = @s tpMillY
execute as @e[tag=tpAirMill] at @s if score #t2 tpTimer matches 300.. run scoreboard players reset #t2 tpTimer