#######
# Compiled from /tpsolar/functions/main.mcscript
# to .//tpsolar/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpSolar] at @s run scoreboard players add @s tpTimer 1
execute as @e[tag=tpSolar] at @s run execute if entity @p[distance=..4] run execute if block ~ ~ ~ air run tag @s remove tpCableConnector
execute as @e[tag=tpSolar] at @s run execute if entity @p[distance=..4] run execute if block ~ ~ ~ air run execute positioned ~ ~-1 ~ as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpSolar] at @s run execute if entity @p[distance=..4] run execute if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:carrot_on_a_stick",Count:1,tag:{id:102s,Unbreakable:1b,Damage:4,HideFlags:4,Stackable:1b,maxStack:64s,AttributeModifiers:[{UUIDMost:-1,UUIDLeast:-1,Amount:1,Slot:"mainhand",AttributeName:"generic.followRange",Operation:0,Name:"stack"}],display:{Name:"{\"text\":\"§5Solar Panel\"}"}}}}
execute as @e[tag=tpSolar] at @s run execute if entity @p[distance=..4] run execute if block ~ ~ ~ air run kill @s
execute as @e[tag=tpSolar] at @s run execute if score @s tpTimer matches 200.. run function tpsolar:solarmain
execute as @e[tag=tpSolar] at @s run execute if score @s tpTimer matches 200.. run scoreboard players reset @s tpTimer
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:4,Damage:4}}}] at @s run tag @s add tpRayFail
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:4,Damage:4}}}] at @s run function tpsolar:place
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:4,Damage:4}}}] at @s run execute if entity @s[tag=!tpRayFail] run tag @s add tpRaySuccess
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:4,Damage:4}}}] at @s run execute if entity @s[tag=tpRayFail] run tag @s remove tpRayFail
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:4,Damage:4}}}] at @s run scoreboard players reset @s tpClick
execute as @a[tag=tpRaySuccess] run function stack:remove
execute as @a[tag=tpRaySuccess] run tag @s remove tpRaySuccess