#######
# Compiled from /tpsolar/functions/solarmain.mcscript
# to .//tpsolar/functions/solarmain.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if block ~ ~1 ~ daylight_detector[inverted=true] run setblock ~ ~1 ~ daylight_detector
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if block ~ ~1 ~ daylight_detector[power=15] run scoreboard players add @e[tag=tpCable,distance=..0.8,limit=1] tpE 1
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if entity @s[tag=tpSolarNext] run scoreboard players add @e[tag=tpCable,distance=..0.8,limit=1] tpE 1
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if entity @s[tag=tpSolarNext] run tag @s remove tpSolarNext
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if entity @s[tag=tpSolarNext2] run tag @s add tpSolarNext
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if entity @s[tag=tpSolarNext2] run tag @s remove tpSolarNext2
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if block ~ ~1 ~ daylight_detector[power=14] run tag @s add tpSolarNext
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if block ~ ~1 ~ daylight_detector[power=13] run tag @s add tpSolarNext
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if block ~ ~1 ~ daylight_detector[power=12] run tag @s add tpSolarNext
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if block ~ ~1 ~ daylight_detector[power=11] run tag @s add tpSolarNext2
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if block ~ ~1 ~ daylight_detector[power=10] run tag @s add tpSolarNext2
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if block ~ ~1 ~ daylight_detector[power=9] run tag @s add tpSolarNext2
execute positioned ~ ~-1 ~ if entity @e[tag=tpCable,distance=..0.8] if block ~ ~1 ~ daylight_detector[power=8] run tag @s add tpSolarNext2