#######
# Compiled from .//functions/main.mcscript
# to .//functions/filtermain.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:3390021,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Item Filter\",\"italic\":false,\"color\":\"gray\"}"},Fireworks:{}}}}
execute if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:gray_stained_glass_pane",tag:{placeholder:1}}}]
execute if block ~ ~ ~ air run kill @s

execute unless data block ~ ~ ~ Items[{Slot:0b}] run replaceitem block ~ ~ ~ container.0 gray_stained_glass_pane{placeholder:1}

execute unless data block ~ ~ ~ Items[{Slot:1b}] run clear @a[distance=..4] gray_stained_glass_pane{placeholder:1}
execute unless data block ~ ~ ~ Items[{Slot:1b}] run replaceitem block ~ ~ ~ container.1 gray_stained_glass_pane{placeholder:1,display:{Name:"{\"text\":\"Do not use this slot.\",\"italic\":false,\"color\":\"gray\"}"}}

execute unless data block ~ ~ ~ Items[{Slot:2b}] run clear @a[distance=..4] gray_stained_glass_pane{placeholder:1}
execute unless data block ~ ~ ~ Items[{Slot:2b}] run replaceitem block ~ ~ ~ container.2 gray_stained_glass_pane{placeholder:1,display:{Name:"{\"text\":\"Do not use this slot.\",\"italic\":false,\"color\":\"gray\"}"}}

execute unless data block ~ ~ ~ Items[{Slot:3b}] run clear @a[distance=..4] gray_stained_glass_pane{placeholder:1}
execute unless data block ~ ~ ~ Items[{Slot:3b}] run replaceitem block ~ ~ ~ container.3 gray_stained_glass_pane{placeholder:1,display:{Name:"{\"text\":\"Do not use this slot.\",\"italic\":false,\"color\":\"gray\"}"}}

execute unless data block ~ ~ ~ Items[{Slot:4b}] run clear @a[distance=..4] gray_stained_glass_pane{placeholder:1}
execute unless data block ~ ~ ~ Items[{Slot:4b}] run replaceitem block ~ ~ ~ container.4 gray_stained_glass_pane{placeholder:1,display:{Name:"{\"text\":\"Do not use this slot.\",\"italic\":false,\"color\":\"gray\"}"}}

execute if block ~ ~ ~ hopper{Items:[{id:"minecraft:gray_stained_glass_pane",tag:{placeholder:1},Slot:0b}]} run replaceitem block ~ ~ ~ container.0 air
