#######
# Compiled from .//functions/create.mcscript
# to .//functions/create.mcfunction
#
# Generated by Minecraft Script for 1.13
######
setblock ~ ~ ~ snow[layers=2]
execute if entity @s[y_rotation=-45..44.99] run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [tpBelt,tpBeltS,tpBeltMove,tpNew],Invisible:1,Marker:1,NoGravity:1}

execute if entity @s[y_rotation=45..134.99] run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [tpBelt,tpBeltW,tpBeltMove,tpNew],Invisible:1,Marker:1,NoGravity:1,Rotation:[90f,0f]}

execute if entity @s[y_rotation=135..-135.01] run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [tpBelt,tpBeltN,tpBeltMove,tpNew],Invisible:1,Marker:1,NoGravity:1,Rotation:[180f,0f]}

execute if entity @s[y_rotation=-135..-45] run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [tpBelt,tpBeltE,tpBeltMove,tpNew],Invisible:1,Marker:1,NoGravity:1,Rotation:[-90f,0f]}

execute as @e[tag=tpBelt,tag=tpNew] at @s run replaceitem entity @s armor.head minecraft:firework_rocket{CustomModelData:3390019}
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^1 ^ ^ if entity @e[tag=tpBelt,distance=..0.75] run replaceitem entity @s armor.head minecraft:iron_pickaxe{CustomModelData:3390004}
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^-1 ^ ^ if entity @e[tag=tpBelt,distance=..0.75] run replaceitem entity @s armor.head minecraft:iron_pickaxe{CustomModelData:3390005}
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^1 ^-1 ^ if entity @e[tag=tpBelt,distance=..0.75] run replaceitem entity @s armor.head minecraft:iron_pickaxe{CustomModelData:3390004}
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^-1 ^-1 ^ if entity @e[tag=tpBelt,distance=..0.75] run replaceitem entity @s armor.head minecraft:iron_pickaxe{CustomModelData:3390005}
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^-1 ^ ^ if entity @e[tag=tpBelt,distance=..0.4] positioned ^2 ^ ^ if entity @e[tag=tpBelt,distance=..0.4] run replaceitem entity @s armor.head minecraft:iron_pickaxe{CustomModelData:3390006}
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 if entity @e[tag=tpBeltUpUpper,distance=..0.75] positioned ^ ^ ^-1 run tp @s ~ ~-0.49 ~
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 if entity @e[tag=tpBeltUpUpper,distance=..0.75] run replaceitem entity @s armor.head minecraft:iron_pickaxe{CustomModelData:3390003}
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 if entity @e[tag=tpBeltUpUpper,distance=..0.75] run tag @s add tpBeltUpLower
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 if entity @e[tag=tpBeltUpUpper,distance=..0.75] run tag @s add tpBeltUp
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 unless block ~ ~ ~ air unless entity @e[tag=tpBelt,distance=..0.5] run replaceitem entity @s armor.head minecraft:iron_pickaxe{CustomModelData:3390003}
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 unless block ~ ~ ~ air unless entity @e[tag=tpBelt,distance=..0.5] positioned ^ ^ ^-1 run setblock ~ ~ ~ snow[layers=6]
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 unless block ~ ~ ~ air unless entity @e[tag=tpBelt,distance=..0.5] run tag @s add tpBeltUpUpper
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 unless block ~ ~ ~ air unless entity @e[tag=tpBelt,distance=..0.5] run tag @s add tpBeltUp
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 unless block ~ ~ ~ air unless entity @e[tag=tpBelt,distance=..0.5] positioned ^ ^ ^-2 as @e[tag=tpBelt,tag=!tpBeltUp,distance=..0.75] at @s run tp @s ~ ~-0.49 ~
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 unless block ~ ~ ~ air unless entity @e[tag=tpBelt,distance=..0.5] positioned ^ ^ ^-2 as @e[tag=tpBelt,tag=!tpBeltUp,distance=..0.75] at @s run replaceitem entity @s armor.head minecraft:iron_pickaxe{CustomModelData:3390003}
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 unless block ~ ~ ~ air unless entity @e[tag=tpBelt,distance=..0.5] positioned ^ ^ ^-2 as @e[tag=tpBelt,tag=!tpBeltUp,distance=..0.75] at @s run tag @s add tpBeltUpLower
execute as @e[tag=tpBelt,tag=tpNew] at @s positioned ^ ^ ^1 unless block ~ ~ ~ air unless entity @e[tag=tpBelt,distance=..0.5] positioned ^ ^ ^-2 as @e[tag=tpBelt,tag=!tpBeltUp,distance=..0.75] at @s run tag @s add tpBeltUp
execute as @e[tag=tpBelt,tag=tpNew] at @s run scoreboard players set #t2 tpTimer 294
execute as @e[tag=tpBelt,tag=tpNew] at @s run tag @s remove tpNew