#######
# Compiled from /tekpack/functions/load.mcscript
# to .//tekpack/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives add tpEDisplay dummy
function tpcables:load
function tpcraft:load
function tpbattery:load
function tpsolar:load
function stack:setup