#######
# Compiled from /tekpack/functions/load.mcscript
# to .//tekpack/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function tekpack:mcscript/load

scoreboard objectives add tpEDisplay dummy
function tpcables:load
function tpcraft:load
function tpbattery:load
function tpsolar:load
function tpbreaker:load
function tpfurn:load
function tphopper:load
function tpdrill:load
function tpgen:load
function stack:setup