#######
# Compiled from /tpdrill/functions/create.mcscript
# to .//tpdrill/functions/create.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute align xyz unless block ~ ~-1 ~ #tpdrill:undestroy run setblock ~ ~ ~ stone_brick_stairs[half=top,shape=inner_left]
execute align xyz unless block ~ ~-1 ~ #tpdrill:undestroy run setblock ~ ~-1 ~ air destroy
execute align xyz unless block ~ ~-1 ~ #tpdrill:undestroy run setblock ~ ~-1 ~ end_rod[facing=down]
execute align xyz run summon armor_stand ~0.5 ~0.4 ~0.5 {Tags: [tpDrill,tpDrillSetup,tpNew,tpCableConnector,tpCableNoConnectD],Invisible:1,Marker:1,NoGravity:1}
execute if entity @s[y_rotation=45..134.99] as @e[tag=tpDrill,tag=tpNew,distance=..5,limit=1] at @s run tp @s ~ ~ ~ 90 0

execute if entity @s[y_rotation=135..-135.01] as @e[tag=tpDrill,tag=tpNew,distance=..5,limit=1] at @s run tp @s ~ ~ ~ 180 0

execute if entity @s[y_rotation=-135..-45] as @e[tag=tpDrill,tag=tpNew,distance=..5,limit=1] at @s run tp @s ~ ~ ~ -90 0

execute as @e[tag=tpDrill,tag=tpNew] at @s run scoreboard players set @s tpE 0
execute as @e[tag=tpDrill,tag=tpNew] at @s run tp @s ~ ~0.1 ~
execute as @e[tag=tpDrill,tag=tpNew] at @s as @e[tag=tpCable,distance=..1.1] at @s run function tpcables:update
execute as @e[tag=tpDrill,tag=tpNew] at @s if block ~ ~-2 ~ air run tag @s remove tpDrillSetup
execute as @e[tag=tpDrill,tag=tpNew] at @s run replaceitem entity @s armor.head minecraft:firework_rocket{CustomModelData:3390011}
execute as @e[tag=tpDrill,tag=tpNew] at @s run tag @s remove tpNew