#######
# Compiled from /tpdrill/functions/load.mcscript
# to .//tpdrill/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function tpdrill:mcscript/load

scoreboard objectives add tpDrillZ dummy
scoreboard objectives add tpDrillTempZ dummy
scoreboard objectives add tpDrillX dummy
scoreboard objectives add tpDrillTempX dummy