#######
# Compiled from .//functions/load.mcscript
# to .//functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function :mcscript/load

scoreboard objectives add tpDrillZ dummy
scoreboard objectives add tpDrillTempZ dummy
scoreboard objectives add tpDrillX dummy
scoreboard objectives add tpDrillTempX dummy