#######
# Compiled from /tpdrill/functions/main.mcscript
# to .//tpdrill/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpDrill] at @s if block ~ ~ ~ air run tag @s add tpBroken
execute as @e[tag=tpDrill] at @s if block ~ ~-1 ~ air run tag @s add tpBroken
execute as @e[tag=tpDrill] at @s if entity @s[tag=tpBroken] run tag @s remove tpCableConnector
execute as @e[tag=tpDrill] at @s if entity @s[tag=tpBroken] as @e[tag=tpCable,distance=..1.1] at @s run function tpcables:update
execute as @e[tag=tpDrill] at @s if entity @s[tag=tpBroken] unless block ~ ~-1 ~ #tpdrill:undestroy run fill ~ ~1 ~ ~ ~-1 ~ air destroy
execute as @e[tag=tpDrill] at @s if entity @s[tag=tpBroken] run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:3390011,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Drill\",\"italic\":false,\"color\":\"dark_purple\"}"},Fireworks:{}}}}
execute as @e[tag=tpDrill] at @s if entity @s[tag=tpBroken] run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:stone_brick_stairs"}}]
execute as @e[tag=tpDrill] at @s if entity @s[tag=tpBroken] positioned ~ ~-1 ~ run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:end_rod"}}]
execute as @e[tag=tpDrill] at @s if entity @s[tag=tpBroken] positioned ~-0.5 ~ ~-0.5 run kill @e[tag=tpDrillPipe,dx=1,dz=1,y=0,dy=256]
execute as @e[tag=tpDrill] at @s if entity @s[tag=tpBroken] run kill @s
execute as @e[tag=tpDrill] at @s if entity @s[tag=tpBroken] run tag @s remove tpBroken
execute as @e[tag=tpDrill] at @s run scoreboard players add @s tpTimer 1
execute as @e[tag=tpDrill] at @s run function tpdrill:powered
execute as @e[tag=tpDrill] at @s run function tpdrill:drillmain
execute as @e[tag=tpDrill] at @s if score @s tpTimer matches 40.. run scoreboard players reset @s tpTimer