#######
# Compiled from .//functions/surface.mcscript
# to .//functions/surface.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[tag=!tpDrillSurfaceFinished] run scoreboard players operation @s tpDrillTempX = @s tpDrillX
execute if entity @s[tag=!tpDrillSurfaceFinished] run scoreboard players operation @s tpDrillTempZ = @s tpDrillZ
execute if entity @s[tag=!tpDrillSurfaceFinished] run function tpdrill:surface_x

scoreboard players add @s tpDrillX 1
execute if score @s tpDrillX matches 7.. run scoreboard players add @s tpDrillZ 1
execute if score @s tpDrillX matches 7.. run scoreboard players set @s tpDrillX 0

execute if score @s tpDrillZ matches 7.. run scoreboard players set @s tpDrillX 0
execute if score @s tpDrillZ matches 7.. run tag @s add tpDrillSurfaceFinished
execute if score @s tpDrillZ matches 7.. run scoreboard players set @s tpDrillZ 0

