#######
# Compiled from .//functions/surface.mcscript
# to .//functions/surface_break.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if block ~ ~ ~ #tpdrill:undestroy_air run scoreboard players add @s[scores={tpE=0..}] tpE 1
execute if block ~ ~ ~ #tpdrill:undestroy run tag @s add tpDrillStopped
execute unless block ~ ~ ~ #tpdrill:undestroy_air run setblock ~ ~ ~ air destroy
execute as @e[type=item,distance=..1] run data merge entity @s {Item:{tag:{tpDrill:1b}}}
tp @e[type=item,distance=..1] @s