#######
# Compiled from .//functions/main.mcscript
# to .//functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpBreaker] at @s if block ~ ~ ~ air run tag @s remove tpCableConnector
execute as @e[tag=tpBreaker] at @s if block ~ ~ ~ air as @e[tag=tpCable,distance=..1.1] at @s run function tpcables:update
execute as @e[tag=tpBreaker] at @s if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:3390009,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Block Breaker\",\"italic\":false,\"color\":\"dark_purple\"}"},Fireworks:{}}}}
execute as @e[tag=tpBreaker] at @s if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:quartz_stairs"}}]
execute as @e[tag=tpBreaker] at @s if block ~ ~ ~ air run kill @s
execute as @e[tag=tpBreaker] at @s run scoreboard players add @s tpTimer 1
execute as @e[tag=tpBreaker] at @s run function tpbreaker:powered
execute as @e[tag=tpBreaker] at @s run function tpbreaker:breakmain
execute as @e[tag=tpBreaker] at @s if score @s tpTimer matches 100.. run scoreboard players reset @s tpTimer