#######
# Compiled from /tpbattery/functions/load.mcscript
# to .//tpbattery/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function tpbattery:mcscript/load

scoreboard objectives add tpBattMax dummy
scoreboard objectives add tpBattMulti dummy
scoreboard players set #15 tpE 15
scoreboard players set #5 tpE 5
scoreboard players set #100 tpE 100