#######
# Compiled from .//functions/main.mcscript
# to .//functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpBattery] at @s if entity @p[distance=..4] if block ~ ~ ~ air run tag @s remove tpCableConnector
execute as @e[tag=tpBattery] at @s if entity @p[distance=..4] if block ~ ~ ~ air positioned ^ ^ ^1 as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpBattery] at @s if entity @p[distance=..4] if block ~ ~ ~ air positioned ^ ^ ^-1 as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpBattery] at @s if entity @p[distance=..4] if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:stone_hoe",tag:{battDisplay:1b}}}]
execute as @e[tag=tpBattery] at @s if entity @p[distance=..4] if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:dropper"}}]
execute as @e[tag=tpBattery] at @s if entity @p[distance=..4] if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:3390003,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Battery\",\"italic\":false,\"color\":\"green\"}"},Fireworks:{}}}}
execute as @e[tag=tpBattery] at @s if entity @p[distance=..4] if block ~ ~ ~ air run kill @s
execute as @e[tag=tpBattery] at @s run function tpbattery:powered
execute as @e[tag=tpBattery] at @s run function tpbattery:batmain
execute as @e[type=item,nbt={Item:{id:"minecraft:stone_hoe",tag:{Unbreakable:1b,battDisplay:1b}}}] at @s if entity @e[tag=tpBattery,distance=..1.4] run kill @s