#######
# Compiled from /tpwatmill/functions/load.mcscript
# to .//tpwatmill/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function tpwatmill:mcscript/load

scoreboard objectives add tpMillY dummy