#######
# Compiled from /tpcables/functions/place.mcscript
# to .//tpcables/functions/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set raycast1 mcscript_raycast 0
execute positioned ~ ~1.5 ~ run function tpwatmill:place_ray
