#######
# Compiled from .//functions/create.mcscript
# to .//functions/create.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[y_rotation=-45..44.99] run summon armor_stand ~0.5 ~1.5 ~0.5 {Tags: [tpGenerator,tpNew,tpCableConnector,tpHigher],Invisible:1,Marker:1,NoGravity:1,Rotation:[180f,0f]}
execute if entity @s[y_rotation=-45..44.99] run setblock ~ ~ ~ furnace[facing=north]{CustomName:"{\"text\":\"Generator\"}"}

execute if entity @s[y_rotation=45..134.99] run summon armor_stand ~0.5 ~1.5 ~0.5 {Tags: [tpGenerator,tpNew,tpCableConnector,tpHigher],Invisible:1,Marker:1,NoGravity:1,Rotation:[-90f,0f]}
execute if entity @s[y_rotation=45..134.99] run setblock ~ ~ ~ furnace[facing=east]{CustomName:"{\"text\":\"Generator\"}"}

execute if entity @s[y_rotation=135..-135.01] run summon armor_stand ~0.5 ~1.5 ~0.5 {Tags: [tpGenerator,tpNew,tpCableConnector,tpHigher],Invisible:1,Marker:1,NoGravity:1}
execute if entity @s[y_rotation=135..-135.01] run setblock ~ ~ ~ furnace[facing=south]{CustomName:"{\"text\":\"Generator\"}"}

execute if entity @s[y_rotation=-135..-45] run summon armor_stand ~0.5 ~1.5 ~0.5 {Tags: [tpGenerator,tpNew,tpCableConnector,tpHigher],Invisible:1,Marker:1,NoGravity:1,Rotation:[90f,0f]}
execute if entity @s[y_rotation=-135..-45] run setblock ~ ~ ~ furnace[facing=west]{CustomName:"{\"text\":\"Generator\"}"}

execute as @e[tag=tpGenerator,tag=tpNew] at @s run scoreboard players set @s tpE 0
execute as @e[tag=tpGenerator,tag=tpNew] at @s positioned ~ ~-1 ~ as @e[tag=tpCable,distance=..1.1] at @s run function tpcables:update
execute as @e[tag=tpGenerator,tag=tpNew] at @s run replaceitem entity @s armor.head minecraft:firework_rocket{CustomModelData:3390004}
execute as @e[tag=tpGenerator,tag=tpNew] at @s run tag @s remove tpNew