#######
# Compiled from /tpgen/functions/genmain.mcscript
# to .//tpgen/functions/genmain.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless block ~ ~ ~ furnace{Items:[{id:"minecraft:iron_pickaxe",Slot:0b}]} run clear @a[distance=..4] iron_pickaxe{Unbreakable:1b,fromGen:1b}
execute unless block ~ ~ ~ furnace{Items:[{id:"minecraft:iron_pickaxe",Slot:0b}]} run replaceitem block ~ ~ ~ container.0 iron_pickaxe{Unbreakable:1b,fromGen:1b,Damage:3,HideFlags:6,display:{Name:"{\"text\":\"\"}"}}

execute if block ~ ~ ~ furnace{Items:[{id:"minecraft:iron_nugget",Slot:2b}]} run scoreboard players add @s[scores={tpE=..14}] tpE 1
execute if block ~ ~ ~ furnace{Items:[{id:"minecraft:iron_nugget",Slot:2b}]} run replaceitem block ~ ~ ~ container.2 air

execute if score #t tpTimer matches 2.. unless score @e[tag=tpCable,distance=..1.1,limit=1] tpE matches 0.. if score @s tpE matches 1.. if entity @e[tag=tpCable,distance=..1.1] run tag @s[tag=!tpPowered] add tpBattRemove

execute if entity @s[tag=tpBattRemove] run scoreboard players add @e[tag=tpCable,distance=..1.1,limit=1,sort=random] tpE 1
execute if entity @s[tag=tpBattRemove] run scoreboard players remove @s tpE 1
execute if entity @s[tag=tpBattRemove] run tag @s remove tpBattRemove
