#######
# Compiled from .//functions/main.mcscript
# to .//functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpGenerator] at @s positioned ~ ~-1 ~ if block ~ ~ ~ air run tag @s remove tpCableConnector
execute as @e[tag=tpGenerator] at @s positioned ~ ~-1 ~ if block ~ ~ ~ air as @e[tag=tpCable,distance=..1.1] at @s run function tpcables:update
execute as @e[tag=tpGenerator] at @s positioned ~ ~-1 ~ if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:3390004,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Generator\",\"italic\":false,\"color\":\"green\"}"},Fireworks:{}}}}
execute as @e[tag=tpGenerator] at @s positioned ~ ~-1 ~ if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:iron_pickaxe",tag:{CustomModelData:3390002}}}]
execute as @e[tag=tpGenerator] at @s positioned ~ ~-1 ~ if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:furnace"}}]
execute as @e[tag=tpGenerator] at @s positioned ~ ~-1 ~ if block ~ ~ ~ air run kill @s
execute as @e[tag=tpGenerator] at @s positioned ~ ~-1 ~ run function tpgen:powered
execute as @e[tag=tpGenerator] at @s positioned ~ ~-1 ~ run function tpgen:genmain