#######
# Compiled from .//functions/powered.mcscript
# to .//functions/powered.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[tag=tpFirstPower] run function tpbattery:items
execute if entity @s[tag=tpFirstPower] positioned ~ ~0.4 ~ run kill @e[type=item,nbt={Item:{id:"minecraft:stone_hoe",tag:{Unbreakable:1b}}}]

tag @s[tag=!tpPowered] add tpFirstPower
tag @s remove tpPowered
execute if block ~ ~-1 ~ minecraft:redstone_torch[lit=true] run tag @s add tpPowered

execute if block ^1 ^ ^ minecraft:redstone_torch[lit=true] run tag @s add tpPowered

execute if block ^-1 ^ ^ minecraft:redstone_torch[lit=true] run tag @s add tpPowered

execute if block ~ ~-1 ~ minecraft:redstone_wall_torch[lit=true] run tag @s add tpPowered

execute if block ^1 ^ ^ minecraft:redstone_wall_torch[lit=true] run tag @s add tpPowered

execute if block ^-1 ^ ^ minecraft:redstone_wall_torch[lit=true] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_block run tag @s add tpPowered

execute if block ~ ~-1 ~ minecraft:redstone_block run tag @s add tpPowered

execute if block ^1 ^ ^ minecraft:redstone_block run tag @s add tpPowered

execute if block ^-1 ^ ^ minecraft:redstone_block run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=1] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=2] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=3] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=4] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=5] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=6] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=7] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=8] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=9] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=10] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=11] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=12] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=13] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=14] run tag @s add tpPowered

execute if block ~ ~1 ~ minecraft:redstone_wire[power=15] run tag @s add tpPowered

tag @s[tag=!tpPowered] remove tpFirstPower