#######
# Compiled from /tpcraft/functions/chestmain2.mcscript
# to .//tpcraft/functions/chestmain2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute unless block ~1 ~ ~ air if entity @e[tag=!tpCraftBlockE] run setblock ~ ~ ~ chest
execute unless block ~1 ~ ~ air if entity @e[tag=!tpCraftBlockE] run data merge block ~ ~ ~ {CustomName:"{\"text\":\"Crafting\"}"}
execute unless block ~1 ~ ~ air if entity @e[tag=!tpCraftBlockE] run tag @s add tpCraftBlockE

execute if block ~1 ~ ~ air if entity @e[tag=tpCraftBlockE] run setblock ~ ~ ~ chest
execute if block ~1 ~ ~ air if entity @e[tag=tpCraftBlockE] run data merge block ~ ~ ~ {CustomName:"{\"text\":\"Crafting\"}"}
execute if block ~1 ~ ~ air if entity @e[tag=tpCraftBlockE] run tag @s remove tpCraftBlockE


execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:0b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:0b}]} run replaceitem block ~ ~ ~ container.0 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:9b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:9b}]} run replaceitem block ~ ~ ~ container.9 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:18b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:18b}]} run replaceitem block ~ ~ ~ container.18 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:4b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:4b}]} run replaceitem block ~ ~ ~ container.4 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:5b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:5b}]} run replaceitem block ~ ~ ~ container.5 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:6b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:6b}]} run replaceitem block ~ ~ ~ container.6 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:7b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:7b}]} run replaceitem block ~ ~ ~ container.7 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:8b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:8b}]} run replaceitem block ~ ~ ~ container.8 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:13b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:13b}]} run replaceitem block ~ ~ ~ container.13 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:14b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:14b}]} run replaceitem block ~ ~ ~ container.14 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:16b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:16b}]} run replaceitem block ~ ~ ~ container.16 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:17b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:17b}]} run replaceitem block ~ ~ ~ container.17 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:22b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:22b}]} run replaceitem block ~ ~ ~ container.22 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:23b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:23b}]} run replaceitem block ~ ~ ~ container.23 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:24b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:24b}]} run replaceitem block ~ ~ ~ container.24 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:25b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:25b}]} run replaceitem block ~ ~ ~ container.25 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{id:"minecraft:gray_stained_glass_pane",Slot:26b}]} run clear @a[distance=..4] minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}} 1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:26b}]} run replaceitem block ~ ~ ~ container.26 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"\"}"}}

# get Count
scoreboard players reset @s tpCraftCount1
scoreboard players reset @s tpCraftCount2
scoreboard players reset @s tpCraftCount3
scoreboard players reset @s tpCraftCount4
scoreboard players reset @s tpCraftCount5
scoreboard players reset @s tpCraftCount6
scoreboard players reset @s tpCraftCount7
scoreboard players reset @s tpCraftCount8
scoreboard players reset @s tpCraftCount9
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:1b}]} run replaceitem block ~ ~ ~ container.1 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:2b}]} run replaceitem block ~ ~ ~ container.2 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:3b}]} run replaceitem block ~ ~ ~ container.3 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:10b}]} run replaceitem block ~ ~ ~ container.10 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:11b}]} run replaceitem block ~ ~ ~ container.11 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:12b}]} run replaceitem block ~ ~ ~ container.12 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} run replaceitem block ~ ~ ~ container.15 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:19b}]} run replaceitem block ~ ~ ~ container.19 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:20b}]} run replaceitem block ~ ~ ~ container.20 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:21b}]} run replaceitem block ~ ~ ~ container.21 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
# Mit item count
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:1b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} unless block ~ ~ ~ minecraft:chest{Items:[{Slot:1b,tag:{Stackable:1b}}]} store result score @s tpCraftCount1 run data get block ~ ~ ~ Items[1].Count
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:2b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} unless block ~ ~ ~ minecraft:chest{Items:[{Slot:2b,tag:{Stackable:1b}}]} store result score @s tpCraftCount2 run data get block ~ ~ ~ Items[2].Count
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:3b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} unless block ~ ~ ~ minecraft:chest{Items:[{Slot:3b,tag:{Stackable:1b}}]} store result score @s tpCraftCount3 run data get block ~ ~ ~ Items[3].Count
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:10b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} unless block ~ ~ ~ minecraft:chest{Items:[{Slot:10b,tag:{Stackable:1b}}]} store result score @s tpCraftCount4 run data get block ~ ~ ~ Items[10].Count
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:11b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} unless block ~ ~ ~ minecraft:chest{Items:[{Slot:11b,tag:{Stackable:1b}}]} store result score @s tpCraftCount5 run data get block ~ ~ ~ Items[11].Count
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:12b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} unless block ~ ~ ~ minecraft:chest{Items:[{Slot:12b,tag:{Stackable:1b}}]} store result score @s tpCraftCount6 run data get block ~ ~ ~ Items[12].Count
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:19b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} unless block ~ ~ ~ minecraft:chest{Items:[{Slot:19b,tag:{Stackable:1b}}]} store result score @s tpCraftCount7 run data get block ~ ~ ~ Items[19].Count
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:20b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} unless block ~ ~ ~ minecraft:chest{Items:[{Slot:20b,tag:{Stackable:1b}}]} store result score @s tpCraftCount8 run data get block ~ ~ ~ Items[20].Count
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:21b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} unless block ~ ~ ~ minecraft:chest{Items:[{Slot:21b,tag:{Stackable:1b}}]} store result score @s tpCraftCount9 run data get block ~ ~ ~ Items[21].Count
# Mit Shades Stack addon
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:1b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:1b,tag:{Stackable:1b}}]} store result score @s tpCraftCount1 run data get block ~ ~ ~ Items[1].tag.AttributeModifiers[0].Amount
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:2b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:2b,tag:{Stackable:1b}}]} store result score @s tpCraftCount2 run data get block ~ ~ ~ Items[2].tag.AttributeModifiers[0].Amount
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:3b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:3b,tag:{Stackable:1b}}]} store result score @s tpCraftCount3 run data get block ~ ~ ~ Items[3].tag.AttributeModifiers[0].Amount
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:10b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:10b,tag:{Stackable:1b}}]} store result score @s tpCraftCount4 run data get block ~ ~ ~ Items[10].tag.AttributeModifiers[0].Amount
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:11b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:11b,tag:{Stackable:1b}}]} store result score @s tpCraftCount5 run data get block ~ ~ ~ Items[11].tag.AttributeModifiers[0].Amount
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:12b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:12b,tag:{Stackable:1b}}]} store result score @s tpCraftCount6 run data get block ~ ~ ~ Items[12].tag.AttributeModifiers[0].Amount
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:19b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:19b,tag:{Stackable:1b}}]} store result score @s tpCraftCount7 run data get block ~ ~ ~ Items[19].tag.AttributeModifiers[0].Amount
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:20b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:20b,tag:{Stackable:1b}}]} store result score @s tpCraftCount8 run data get block ~ ~ ~ Items[20].tag.AttributeModifiers[0].Amount
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:21b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:21b,tag:{Stackable:1b}}]} store result score @s tpCraftCount9 run data get block ~ ~ ~ Items[21].tag.AttributeModifiers[0].Amount
# wenn Item herausgenommen wird
scoreboard players reset @s tpCraftTake
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if entity @s[tag=tpCraftSuccess] unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,tag:{Stackable:1b}}]} store result score @s tpCraftTake run data get block ~ ~ ~ Items[15].Count -1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if entity @s[tag=tpCraftSuccess] unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,tag:{Stackable:1b}}]} run scoreboard players operation @s tpCraftTake += @s tpCraftCountLow

execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if entity @s[tag=tpCraftSuccess] run scoreboard players operation @s tpCraftTake = @s tpCraftCountLow

execute if score @s tpCraftTake matches 1.. run say ok
execute if score @s tpCraftTake matches 1.. if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount1 matches 1.. run scoreboard players operation @s tpCraftCount1 -= @s tpCraftTake
execute if score @s tpCraftTake matches 1.. if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount2 matches 1.. run scoreboard players operation @s tpCraftCount2 -= @s tpCraftTake
execute if score @s tpCraftTake matches 1.. if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount3 matches 1.. run scoreboard players operation @s tpCraftCount3 -= @s tpCraftTake
execute if score @s tpCraftTake matches 1.. if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount4 matches 1.. run scoreboard players operation @s tpCraftCount4 -= @s tpCraftTake
execute if score @s tpCraftTake matches 1.. if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount5 matches 1.. run scoreboard players operation @s tpCraftCount5 -= @s tpCraftTake
execute if score @s tpCraftTake matches 1.. if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount6 matches 1.. run scoreboard players operation @s tpCraftCount6 -= @s tpCraftTake
execute if score @s tpCraftTake matches 1.. if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount7 matches 1.. run scoreboard players operation @s tpCraftCount7 -= @s tpCraftTake
execute if score @s tpCraftTake matches 1.. if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount8 matches 1.. run scoreboard players operation @s tpCraftCount8 -= @s tpCraftTake
execute if score @s tpCraftTake matches 1.. if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount9 matches 1.. run scoreboard players operation @s tpCraftCount9 -= @s tpCraftTake
execute if score @s tpCraftTake matches 1.. if entity @s[tag=tpCraftNoStack] if score @s tpCraftCount1 matches 1.. run scoreboard players remove @s tpCraftCount1 1
execute if score @s tpCraftTake matches 1.. if entity @s[tag=tpCraftNoStack] if score @s tpCraftCount2 matches 1.. run scoreboard players remove @s tpCraftCount2 1
execute if score @s tpCraftTake matches 1.. if entity @s[tag=tpCraftNoStack] if score @s tpCraftCount3 matches 1.. run scoreboard players remove @s tpCraftCount3 1
execute if score @s tpCraftTake matches 1.. if entity @s[tag=tpCraftNoStack] if score @s tpCraftCount4 matches 1.. run scoreboard players remove @s tpCraftCount4 1
execute if score @s tpCraftTake matches 1.. if entity @s[tag=tpCraftNoStack] if score @s tpCraftCount5 matches 1.. run scoreboard players remove @s tpCraftCount5 1
execute if score @s tpCraftTake matches 1.. if entity @s[tag=tpCraftNoStack] if score @s tpCraftCount6 matches 1.. run scoreboard players remove @s tpCraftCount6 1
execute if score @s tpCraftTake matches 1.. if entity @s[tag=tpCraftNoStack] if score @s tpCraftCount7 matches 1.. run scoreboard players remove @s tpCraftCount7 1
execute if score @s tpCraftTake matches 1.. if entity @s[tag=tpCraftNoStack] if score @s tpCraftCount8 matches 1.. run scoreboard players remove @s tpCraftCount8 1
execute if score @s tpCraftTake matches 1.. if entity @s[tag=tpCraftNoStack] if score @s tpCraftCount9 matches 1.. run scoreboard players remove @s tpCraftCount9 1
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount1 matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:1b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[1].Count byte 1 run scoreboard players get @s tpCraftCount1
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount1 matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:1b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[1].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCount1
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount1 matches ..0 run replaceitem block ~ ~ ~ container.1 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount2 matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:2b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[2].Count byte 1 run scoreboard players get @s tpCraftCount2
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount1 matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:2b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[2].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCount2
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount2 matches ..0 run replaceitem block ~ ~ ~ container.2 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount3 matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:3b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[3].Count byte 1 run scoreboard players get @s tpCraftCount3
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount3 matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:3b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[3].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCount3
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount3 matches ..0 run replaceitem block ~ ~ ~ container.3 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount4 matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:10b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[10].Count byte 1 run scoreboard players get @s tpCraftCount4
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount4 matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:10b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[10].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCount4
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount4 matches ..0 run replaceitem block ~ ~ ~ container.10 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount5 matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:11b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[11].Count byte 1 run scoreboard players get @s tpCraftCount5
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount5 matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:11b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[11].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCount5
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount5 matches ..0 run replaceitem block ~ ~ ~ container.11 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount6 matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:12b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[12].Count byte 1 run scoreboard players get @s tpCraftCount6
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount6 matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:12b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[12].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCount6
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount6 matches ..0 run replaceitem block ~ ~ ~ container.12 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount7 matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:19b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[19].Count byte 1 run scoreboard players get @s tpCraftCount7
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount7 matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:19b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[19].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCount7
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount7 matches ..0 run replaceitem block ~ ~ ~ container.19 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount8 matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:20b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[20].Count byte 1 run scoreboard players get @s tpCraftCount8
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount8 matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:20b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[20].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCount8
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount8 matches ..0 run replaceitem block ~ ~ ~ container.20 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount9 matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:21b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[21].Count byte 1 run scoreboard players get @s tpCraftCount9
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount9 matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:21b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[21].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCount9
execute if score @s tpCraftTake matches 1.. if score @s tpCraftCount9 matches ..0 run replaceitem block ~ ~ ~ container.21 minecraft:gray_stained_glass_pane{display:{Name:"{\"text\":\"placeholder\"}"}}
execute if score @s tpCraftTake matches 1.. run tag @s remove tpCraftSuccess

replaceitem block ~ ~ ~ container.15 air
tag @s remove tpCraftSuccess
tag @s remove tpCraftNoStack
function #tpcraft:recipes
execute if entity @s[scores={tpCraftID=1..}] run function #tpcraft:results

scoreboard players reset @s tpCraftCountLow
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} run tag @s add tpCraftSuccess
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] unless score @s tpCraftCountLow matches 1.. run scoreboard players operation @s tpCraftCountLow = @s tpCraftCount1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount1 matches 1.. run scoreboard players operation @s tpCraftCountLow < @s tpCraftCount1
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] unless score @s tpCraftCountLow matches 1.. run scoreboard players operation @s tpCraftCountLow = @s tpCraftCount2
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount2 matches 1.. run scoreboard players operation @s tpCraftCountLow < @s tpCraftCount2
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] unless score @s tpCraftCountLow matches 1.. run scoreboard players operation @s tpCraftCountLow = @s tpCraftCount3
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount3 matches 1.. run scoreboard players operation @s tpCraftCountLow < @s tpCraftCount3
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] unless score @s tpCraftCountLow matches 1.. run scoreboard players operation @s tpCraftCountLow = @s tpCraftCount4
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount4 matches 1.. run scoreboard players operation @s tpCraftCountLow < @s tpCraftCount4
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] unless score @s tpCraftCountLow matches 1.. run scoreboard players operation @s tpCraftCountLow = @s tpCraftCount5
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount5 matches 1.. run scoreboard players operation @s tpCraftCountLow < @s tpCraftCount5
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] unless score @s tpCraftCountLow matches 1.. run scoreboard players operation @s tpCraftCountLow = @s tpCraftCount6
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount6 matches 1.. run scoreboard players operation @s tpCraftCountLow < @s tpCraftCount6
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] unless score @s tpCraftCountLow matches 1.. run scoreboard players operation @s tpCraftCountLow = @s tpCraftCount7
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount7 matches 1.. run scoreboard players operation @s tpCraftCountLow < @s tpCraftCount7
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] unless score @s tpCraftCountLow matches 1.. run scoreboard players operation @s tpCraftCountLow = @s tpCraftCount8
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount8 matches 1.. run scoreboard players operation @s tpCraftCountLow < @s tpCraftCount8
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] unless score @s tpCraftCountLow matches 1.. run scoreboard players operation @s tpCraftCountLow = @s tpCraftCount9
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCount9 matches 1.. run scoreboard players operation @s tpCraftCountLow < @s tpCraftCount9
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCountLow matches 1.. unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[15].Count byte 1 run scoreboard players get @s tpCraftCountLow
execute unless block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b}]} if entity @s[tag=!tpCraftNoStack] if score @s tpCraftCountLow matches 1.. if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,tag:{Stackable:1b}}]} store result block ~ ~ ~ Items[15].tag.AttributeModifiers[0].Amount int 1 run scoreboard players get @s tpCraftCountLow

execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:1b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.1 air
execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:2b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.2 air
execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:3b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.3 air
execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:10b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.10 air
execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:11b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.11 air
execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:12b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.12 air
execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:15b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.15 air
execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:19b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.19 air
execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:20b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.20 air
execute if block ~ ~ ~ minecraft:chest{Items:[{Slot:21b,id:"minecraft:gray_stained_glass_pane",tag:{display:{Name:"{\"text\":\"placeholder\"}"}}}]} run replaceitem block ~ ~ ~ container.21 air
scoreboard players reset @s tpCraftID