#######
# Compiled from /tpcraft/functions/create.mcscript
# to .//tpcraft/functions/create.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute align xyz run setblock ~ ~ ~ chest[type=left]
execute align xyz run data merge block ~ ~ ~ {CustomName:"{\"text\":\"technical Crafting\"}"}
execute align xyz run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [tpCrafter,tpNew],Invisible:1,Marker:1,NoGravity:1}
execute as @e[tag=tpCrafter,tag=tpNew] at @s run replaceitem entity @s armor.head minecraft:firework_rocket{CustomModelData:3390001}
execute as @e[tag=tpCrafter,tag=tpNew] at @s run tag @s remove tpNew