#######
# Compiled from /tpcraft/functions/load.mcscript
# to .//tpcraft/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function tpcraft:mcscript/load

scoreboard objectives add tpCraftID dummy
scoreboard objectives add mcscript_raycast dummy
scoreboard objectives add tpCraftTake dummy
scoreboard objectives add tpCraftCountLow dummy
scoreboard objectives add tpCraftCount1 dummy
scoreboard objectives add tpCraftCount2 dummy
scoreboard objectives add tpCraftCount3 dummy
scoreboard objectives add tpCraftCount4 dummy
scoreboard objectives add tpCraftCount5 dummy
scoreboard objectives add tpCraftCount6 dummy
scoreboard objectives add tpCraftCount7 dummy
scoreboard objectives add tpCraftCount8 dummy
scoreboard objectives add tpCraftCount9 dummy