#######
# Compiled from /tpcraft/functions/main.mcscript
# to .//tpcraft/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpCrafter] at @s if entity @p[distance=..4] if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:stone_hoe",tag:{display:{Name:"{\"text\":\"\"}"},HideFlags:6}}}]
execute as @e[tag=tpCrafter] at @s if entity @p[distance=..4] if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:chest"}}]
execute as @e[tag=tpCrafter] at @s if entity @p[distance=..4] if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:3390001,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Technical Crafting Table\",\"italic\":false,\"color\":\"dark_purple\"}"},Fireworks:{}}}}
execute as @e[tag=tpCrafter] at @s if entity @p[distance=..4] if block ~ ~ ~ air run kill @s
execute as @e[tag=tpCrafter] at @s if entity @p[distance=..4] run function tpcraft:chestmain
execute as @a[nbt={Inventory:[{id:"minecraft:knowledge_book"}]}] run tag @s add tpCraftBlock
execute as @a[tag=tpCraftBlock] at @s run clear @s knowledge_book 1
execute as @a[tag=tpCraftBlock] at @s run give @s firework_rocket{CustomModelData:3390001,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Technical Crafting Table\",\"italic\":false,\"color\":\"dark_purple\"}"},Fireworks:{}}
execute as @a[tag=tpCraftBlock] at @s run tag @s remove tpCraftBlock