#######
# Compiled from .//functions/main.mcscript
# to .//functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpCrafter] at @s if entity @p[distance=..4] if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:stone_hoe",tag:{Unbreakable:1b}}}]
execute as @e[tag=tpCrafter] at @s if entity @p[distance=..4] if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:carrot_on_a_stick",Count:1,tag:{Unbreakable:1b,Damage:2,HideFlags:6,display:{Name:"{\"text\":\"§5Technical Crafting Table\"}"}}}}
execute as @e[tag=tpCrafter] at @s if entity @p[distance=..4] if block ~ ~ ~ air run kill @s
execute as @e[tag=tpCrafter] at @s if entity @p[distance=..4] run function tpcraft:chestmain
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:6,Damage:2}}}] at @s run tag @s add tpRayFail
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:6,Damage:2}}}] at @s run function tpcraft:place
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:6,Damage:2}}}] at @s if entity @s[tag=!tpRayFail] run tag @s add tpRaySuccess
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:6,Damage:2}}}] at @s if entity @s[tag=tpRayFail] run tag @s remove tpRayFail
execute as @a[scores={tpClick=1..},nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{Unbreakable:1b,HideFlags:6,Damage:2}}}] at @s run scoreboard players reset @s tpClick
execute as @a[tag=tpRaySuccess] run replaceitem entity @s weapon.mainhand air
execute as @a[tag=tpRaySuccess] run tag @s remove tpRaySuccess
execute as @a[nbt={Inventory:[{id:"minecraft:knowledge_book"}]}] run tag @s add tpCraftBlock
execute as @a[tag=tpCraftBlock] at @s run clear @s knowledge_book 1
execute as @a[tag=tpCraftBlock] at @s run give @s carrot_on_a_stick{Unbreakable:1b,Damage:2,HideFlags:6,display:{Name:"{\"text\":\"§5Technical Crafting Table\"}"}}
execute as @a[tag=tpCraftBlock] at @s run tag @s remove tpCraftBlock