#######
# Compiled from data/tekpack/functions/place.mcscript
# to .//data/tekpack/functions/place.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set raycast1 mcscript_raycast 0
execute positioned ~ ~1.5 ~ run function tpcraft:place_ray
