#######
# Compiled from /tphopper/functions/create.mcscript
# to .//tphopper/functions/create.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute align xyz run setblock ~ ~ ~ hopper
execute align xyz run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [tpHopper,tpNew,tpCableConnector,tpCableNoConnectD],Invisible:1,Marker:1,NoGravity:1}
execute as @e[tag=tpHopper,tag=tpNew] at @s run scoreboard players set @s tpE 0
execute as @e[tag=tpHopper,tag=tpNew] at @s run tp @s ~ ~ ~
execute as @e[tag=tpHopper,tag=tpNew] at @s as @e[tag=tpCable,distance=..1.1] at @s run function tpcables:update
execute as @e[tag=tpHopper,tag=tpNew] at @s run replaceitem entity @s armor.head minecraft:carrot_on_a_stick{Unbreakable:1b,Damage:7}
execute as @e[tag=tpHopper,tag=tpNew] at @s run tag @s remove tpNew