#######
# Compiled from .//functions/main.mcscript
# to .//functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpHopper] at @s if block ~ ~ ~ air run tag @s remove tpCableConnector
execute as @e[tag=tpHopper] at @s if block ~ ~ ~ air as @e[tag=tpCable,distance=..1.1] at @s run function tpcables:update
execute as @e[tag=tpHopper] at @s if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:3390010,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Vacuum Hopper\",\"italic\":false,\"color\":\"dark_purple\"}"},Fireworks:{}}}}
execute as @e[tag=tpHopper] at @s if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:hopper"}}]
execute as @e[tag=tpHopper] at @s if block ~ ~ ~ air run kill @s
execute as @e[tag=tpHopper] at @s run scoreboard players add @s tpTimer 1
execute as @e[tag=tpHopper] at @s run function tphopper:powered
execute as @e[tag=tpHopper] at @s run function tphopper:hoppermain
execute as @e[tag=tpHopper] at @s if score @s tpTimer matches 100.. run scoreboard players reset @s tpTimer
execute as @e[type=item,tag=tpHopperAttractNew] at @s run data merge entity @s {NoGravity:1b,Motion:[0,0,0],PickupDelay:40}
execute as @e[type=item,tag=tpHopperAttractNew] at @s run tp @s ~ ~0.1 ~
execute as @e[type=item,tag=tpHopperAttractNew] at @s run tag @s remove tpHopperAttractNew
execute as @e[type=item,tag=tpHopperAttract] at @s unless entity @e[tag=tpHopper,distance=..4] run data merge entity @s {NoGravity:0b,Motion:[0,0,0],PickupDelay:0}
execute as @e[type=item,tag=tpHopperAttract] at @s unless entity @e[tag=tpHopper,distance=..4] run tag @s remove tpHopperAttract
execute as @e[type=item,tag=tpHopperAttract] at @s facing entity @e[tag=tpHopper,distance=..4,sort=nearest,limit=1] eyes run tp @s ~ ~ ~ facing ^ ^ ^1
execute as @e[type=item,tag=tpHopperAttract] at @s run tp @s ^ ^ ^0.1