#######
# Compiled from /tpcables/functions/create.mcscript
# to .//tpcables/functions/create.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute align xyz run summon armor_stand ~0.5 ~0.5 ~0.5 {Tags: [tpCable,tpNew,tpCableConnector],Invisible:1,Marker:1,NoGravity:1}
execute as @e[tag=tpNew,distance=..1,tag=tpCable] at @s positioned ~1 ~ ~ as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpNew,distance=..1,tag=tpCable] at @s positioned ~-1 ~ ~ as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpNew,distance=..1,tag=tpCable] at @s positioned ~ ~1 ~ as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpNew,distance=..1,tag=tpCable] at @s positioned ~ ~-1 ~ as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpNew,distance=..1,tag=tpCable] at @s positioned ~ ~ ~-1 as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpNew,distance=..1,tag=tpCable] at @s positioned ~ ~ ~1 as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpNew,distance=..1,tag=tpCable] at @s run function tpcables:update
execute as @e[tag=tpNew,distance=..1,tag=tpCable] at @s run tag @s remove tpNew
