#######
# Compiled from /tpcables/functions/load.mcscript
# to .//tpcables/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives add tpE dummy
scoreboard objectives add tpTimer dummy
scoreboard objectives add tpCableCount dummy
scoreboard objectives add tpClick minecraft.used:minecraft.carrot_on_a_stick