#######
# Compiled from /tpcables/functions/main.mcscript
# to .//tpcables/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
# 1/2 sec Clock
execute if score #t tpTimer matches 2.. run function tpcables:slow_clock

# Break Event
execute as @e[tag=tpCable] at @s if block ~ ~ ~ air run summon armor_stand ~ ~ ~ {Tags: [tpCableTemp],Invisible:1,Marker:1,NoGravity:1}
execute as @e[tag=tpCable] at @s if block ~ ~ ~ air run kill @e[type=item,distance=..0.5,limit=1,sort=nearest]
execute as @e[tag=tpCable] at @s if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{Fireworks:{},CustomModelData:3390002,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Cable\",\"italic\":false,\"color\":\"dark_purple\"}",Lore:["§aTransfers energy"]}}}}
execute as @e[tag=tpCable] at @s if block ~ ~ ~ air run kill @s
execute as @e[tag=tpCableTemp] at @s positioned ~1 ~ ~ as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpCableTemp] at @s positioned ~-1 ~ ~ as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpCableTemp] at @s positioned ~ ~1 ~ as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpCableTemp] at @s positioned ~ ~-1 ~ as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpCableTemp] at @s positioned ~ ~ ~-1 as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpCableTemp] at @s positioned ~ ~ ~1 as @e[tag=tpCable,distance=..0.8] at @s run function tpcables:update
execute as @e[tag=tpCableTemp] at @s run kill @s
#remove !!!!
#/scoreboard players reset @a tpClick