#######
# Compiled from /tpcables/functions/slowTimer.mcscript
# to .//tpcables/functions/slow_clock.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @e[tag=tpCable,scores={tpE=1..}] add tpCablePowered
execute as @e[tag=tpCablePowered] at @s run particle minecraft:dust 0.2 1 0.2 0.8 ~ ~ ~ 0 0.1 0 10 10
execute as @e[tag=tpCablePowered] at @s run scoreboard players set @s tpCableCount 0
execute as @e[tag=tpCablePowered] at @s run execute at @e[tag=tpCable,distance=0.5..1.01] run scoreboard players add @s tpCableCount 1
execute as @e[tag=tpCablePowered] at @s run execute unless entity @e[tag=tpCable,distance=0.5..1.01,tag=!tpCableSource] run execute if score @s tpCableCount matches 1 run particle minecraft:dust 0.2 1 0.6 1.6 ~ ~ ~ 0 0.2 0 10 10
execute as @e[tag=tpCablePowered] at @s run execute unless entity @e[tag=tpCable,distance=0.5..1.01,tag=!tpCableSource] run tag @e[tag=tpCableSource,distance=0.5..1.01] remove tpCableSource
execute as @e[tag=tpCablePowered] at @s run execute unless entity @e[tag=tpCable,distance=0.5..1.01,tag=!tpCableSource] run scoreboard players reset @s tpCableCount
execute as @e[tag=tpCablePowered] at @s run execute unless entity @e[tag=tpCable,distance=0.5..1.01,tag=!tpCableSource] run tag @s remove tpCablePowered
execute as @e[tag=tpCablePowered] at @s run execute as @e[tag=tpCable,distance=0.5..1.01,limit=1,sort=random,tag=!tpCableSource] run scoreboard players add @s tpE 1
execute as @e[tag=tpCablePowered] at @s run scoreboard players remove @s tpE 1
execute as @e[tag=tpCablePowered] at @s run execute if entity @s[scores={tpE=..0}] run scoreboard players reset @s tpE
execute as @e[tag=tpCablePowered] at @s run tag @e[tag=tpCableSource] remove tpCableSource
execute as @e[tag=tpCablePowered] at @s run tag @s add tpCableSource
execute as @e[tag=tpCablePowered] at @s run tag @s remove tpCablePowered