#######
# Compiled from /tpcables/functions/create.mcscript
# to .//tpcables/functions/update.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set @s tpCableCount 0
tag @s remove tpCableS
tag @s remove tpCableN
tag @s remove tpCableW
tag @s remove tpCableE
tag @s remove tpCableU
tag @s remove tpCableD
tag @s remove tpCableEnd
tag @s remove tpCableEndE
tag @s remove tpCableEndW
tag @s remove tpCableEndN
tag @s remove tpCableEndS
tag @s remove tpCableEndU
tag @s remove tpCableEndD
tag @s remove tpCableStrWE
tag @s remove tpCableStrNS
tag @s remove tpCableStrUD
tag @s remove tpCableAlone
tag @s remove tpCableEnd
tag @s remove tpCableCorner
tag @s remove tpCableStraight
tag @s remove tpCableTInter
tag @s remove tpCableIntersection
replaceitem entity @s weapon.offhand air
replaceitem entity @s weapon.mainhand air
execute positioned ~1 ~ ~ if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectE,distance=..0.8] run tag @s add tpCableE
execute positioned ~1 ~ ~ if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectE,distance=..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~-1 ~ ~ if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectW,distance=..0.8] run tag @s add tpCableW
execute positioned ~-1 ~ ~ if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectW,distance=..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~ ~1 ~ if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectU,distance=..0.8] run tag @s add tpCableU
execute positioned ~ ~1 ~ if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectU,distance=..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~ ~-1 ~ if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectD,distance=..0.8] run tag @s add tpCableD
execute positioned ~ ~-1 ~ if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectD,distance=..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~ ~ ~-1 if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectN,distance=..0.8] run tag @s add tpCableN
execute positioned ~ ~ ~-1 if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectN,distance=..0.8] run replaceitem entity @s weapon.offhand diamond_pickaxe{Damage:10,Unbreakable:1}
execute positioned ~ ~ ~-1 if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectN,distance=..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~ ~ ~1 if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectS,distance=..0.8] run tag @s add tpCableS
execute positioned ~ ~ ~1 if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectS,distance=..0.8] run replaceitem entity @s weapon.offhand diamond_pickaxe{Damage:11,Unbreakable:1}
execute positioned ~ ~ ~1 if entity @e[tag=tpCableConnector,tag=!tpCableNoConnectS,distance=..0.8] run scoreboard players add @s tpCableCount 1
#tooHigh
execute positioned ~1 ~1 ~ if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectE,distance=..0.8] run tag @s add tpCableE
execute positioned ~1 ~1 ~ if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectE,distance=..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~-1 ~1 ~ if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectW,distance=..0.8] run tag @s add tpCableW
execute positioned ~-1 ~1 ~ if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectW,distance=..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~ ~2 ~ if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectU,distance=..0.8] run tag @s add tpCableU
execute positioned ~ ~2 ~ if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectU,distance=..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~ ~ ~ if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectD,distance=0.01..0.8] run tag @s add tpCableD
execute positioned ~ ~ ~ if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectD,distance=0.01..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~ ~1 ~-1 if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectN,distance=..0.8] run tag @s add tpCableN
execute positioned ~ ~1 ~-1 if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectN,distance=..0.8] run replaceitem entity @s weapon.offhand diamond_pickaxe{Damage:10,Unbreakable:1}
execute positioned ~ ~1 ~-1 if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectN,distance=..0.8] run scoreboard players add @s tpCableCount 1
execute positioned ~ ~1 ~1 if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectS,distance=..0.8] run tag @s add tpCableS
execute positioned ~ ~1 ~1 if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectS,distance=..0.8] run replaceitem entity @s weapon.offhand diamond_pickaxe{Damage:11,Unbreakable:1}
execute positioned ~ ~1 ~1 if entity @e[tag=tpCableConnector,tag=tpHigher,tag=!tpCableNoConnectS,distance=..0.8] run scoreboard players add @s tpCableCount 1
# richtige Models laden
execute if entity @s[tag=tpCableN,tag=tpCableS] run replaceitem entity @s weapon.offhand diamond_pickaxe{Damage:9,Unbreakable:1}

execute if entity @s[tag=tpCableE,tag=!tpCableW,tag=!tpCableU] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:4,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=tpCableW,tag=!tpCableU] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:5,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=tpCableU] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:13,Unbreakable:1}

execute if entity @s[tag=tpCableE,tag=!tpCableW,tag=tpCableU] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:7,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=tpCableW,tag=tpCableU] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:6,Unbreakable:1}

execute if entity @s[tag=tpCableE,tag=tpCableW,tag=!tpCableU] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:3,Unbreakable:1}

execute if entity @s[tag=tpCableE,tag=tpCableW,tag=tpCableU] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:8,Unbreakable:1}

replaceitem entity @s armor.head diamond_pickaxe{Damage:1,Unbreakable:1}
execute if entity @s[tag=tpCableE,tag=tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableStraight
execute if entity @s[tag=tpCableE,tag=tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableStrWE
execute if entity @s[tag=tpCableE,tag=tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run setblock ~ ~ ~ minecraft:end_rod[facing=east]
execute if entity @s[tag=tpCableE,tag=tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:3,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=tpCableN,tag=tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableStraight
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=tpCableN,tag=tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableStrNS
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=tpCableN,tag=tpCableS,tag=!tpCableU,tag=!tpCableD] run setblock ~ ~ ~ minecraft:end_rod[facing=north]
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=tpCableN,tag=tpCableS,tag=!tpCableU,tag=!tpCableD] run replaceitem entity @s weapon.offhand diamond_pickaxe{Damage:9,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=tpCableU,tag=tpCableD] run tag @s add tpCableStraight
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=tpCableU,tag=tpCableD] run tag @s add tpCableStrUD
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=tpCableU,tag=tpCableD] run setblock ~ ~ ~ minecraft:end_rod[facing=up]
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=tpCableU,tag=tpCableD] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:12,Unbreakable:1}

execute if score @s tpCableCount matches 0 run tag @s add tpCableAlone
execute if score @s tpCableCount matches 0 run setblock ~ ~ ~ minecraft:flower_pot
execute if score @s tpCableCount matches 0 run replaceitem entity @s armor.head diamond_pickaxe{Damage:2,Unbreakable:1}

execute if score @s tpCableCount matches 2 if entity @s[tag=!tpCableStraight] run tag @s add tpCableCorner
execute if score @s tpCableCount matches 2 if entity @s[tag=!tpCableStraight] run setblock ~ ~ ~ minecraft:flower_pot
execute if score @s tpCableCount matches 2 if entity @s[tag=!tpCableStraight] run replaceitem entity @s armor.head diamond_pickaxe{Damage:2,Unbreakable:1}

execute if score @s tpCableCount matches 3 run tag @s add tpCableTInter
execute if score @s tpCableCount matches 3 run setblock ~ ~ ~ minecraft:flower_pot
execute if score @s tpCableCount matches 3 run replaceitem entity @s armor.head diamond_pickaxe{Damage:2,Unbreakable:1}

execute if score @s tpCableCount matches 4 run tag @s add tpCableIntersection
execute if score @s tpCableCount matches 4 run setblock ~ ~ ~ minecraft:flower_pot
execute if score @s tpCableCount matches 4 run replaceitem entity @s armor.head diamond_pickaxe{Damage:2,Unbreakable:1}

scoreboard players reset @s tpCableCount
execute if entity @s[tag=tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableEnd
execute if entity @s[tag=tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableEndE
execute if entity @s[tag=tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run setblock ~ ~ ~ minecraft:end_rod[facing=west]
execute if entity @s[tag=tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:3,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableEnd
execute if entity @s[tag=!tpCableE,tag=tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableEndW
execute if entity @s[tag=!tpCableE,tag=tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run setblock ~ ~ ~ minecraft:end_rod[facing=east]
execute if entity @s[tag=!tpCableE,tag=tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:3,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableEnd
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableEndN
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run setblock ~ ~ ~ minecraft:end_rod[facing=south]
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=tpCableN,tag=!tpCableS,tag=!tpCableU,tag=!tpCableD] run replaceitem entity @s weapon.offhand diamond_pickaxe{Damage:9,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableEnd
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=tpCableS,tag=!tpCableU,tag=!tpCableD] run tag @s add tpCableEndS
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=tpCableS,tag=!tpCableU,tag=!tpCableD] run setblock ~ ~ ~ minecraft:end_rod[facing=north]
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=tpCableS,tag=!tpCableU,tag=!tpCableD] run replaceitem entity @s weapon.offhand diamond_pickaxe{Damage:9,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=tpCableU,tag=!tpCableD] run tag @s add tpCableEnd
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=tpCableU,tag=!tpCableD] run tag @s add tpCableEndU
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=tpCableU,tag=!tpCableD] run setblock ~ ~ ~ minecraft:end_rod[facing=up]
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=tpCableU,tag=!tpCableD] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:12,Unbreakable:1}

execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=tpCableD] run tag @s add tpCableEnd
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=tpCableD] run tag @s add tpCableEndD
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=tpCableD] run setblock ~ ~ ~ minecraft:end_rod[facing=down]
execute if entity @s[tag=!tpCableE,tag=!tpCableW,tag=!tpCableN,tag=!tpCableS,tag=!tpCableU,tag=tpCableD] run replaceitem entity @s weapon.mainhand diamond_pickaxe{Damage:12,Unbreakable:1}
