#######
# Compiled from /tpcables/functions/update_item.mcscript
# to .//tpcables/functions/update_item.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s tpCableCount matches ..0 run clear @s minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 1 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(1)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 2 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(2)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 3 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(3)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 4 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(4)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 5 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(5)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 6 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(6)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 7 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(7)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 8 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(8)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 9 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(9)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 10 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(10)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 11 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(11)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 12 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(12)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 13 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(13)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 14 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(14)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 15 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(15)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 16 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(16)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 17 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(17)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 18 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(18)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 19 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(19)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 20 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(20)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 21 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(21)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 22 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(22)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 23 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(23)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 24 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(24)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 25 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(25)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 26 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(26)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 27 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(27)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 28 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(28)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 29 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(29)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 30 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(30)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 31 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(31)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 32 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(32)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 33 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(33)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 34 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(34)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 35 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(35)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 36 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(36)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 37 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(37)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 38 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(38)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 39 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(39)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 40 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(40)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 41 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(41)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 42 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(42)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 43 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(43)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 44 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(44)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 45 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(45)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 46 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(46)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 47 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(47)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 48 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(48)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 49 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(49)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 50 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(50)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 51 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(51)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 52 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(52)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 53 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(53)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 54 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(54)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 55 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(55)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 56 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(56)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 57 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(57)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 58 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(58)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 59 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(59)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 60 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(60)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 61 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(61)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 62 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(62)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 63 run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(63)\"}",Lore:["§aTransfers energy"]}}

execute if score @s tpCableCount matches 64.. run replaceitem entity @s weapon.mainhand minecraft:carrot_on_a_stick{Unbreakable:1,Damage:1,display:{Name:"{\"text\":\"§5Cable(64++)\"}",Lore:["§aTransfers energy"]}}
