#######
# Compiled from .//functions/create.mcscript
# to .//functions/create.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[y_rotation=-45..44.99] run setblock ~ ~ ~ stone_stairs[facing=south,half=top]
execute if entity @s[y_rotation=-45..44.99] run summon armor_stand ~0.5 ~0.25 ~0.5 {Tags: [tpExtractor,tpBeltN,tpBeltMove,tpNew],Invisible:1,Marker:1,NoGravity:1,Rotation:[180f,0f]}

execute if entity @s[y_rotation=45..134.99] run setblock ~ ~ ~ stone_stairs[facing=west,half=top]
execute if entity @s[y_rotation=45..134.99] run summon armor_stand ~0.5 ~0.25 ~0.5 {Tags: [tpExtractor,tpBeltE,tpBeltMove,tpNew],Invisible:1,Marker:1,NoGravity:1,Rotation:[-90f,0f]}

execute if entity @s[y_rotation=135..-135.01] run setblock ~ ~ ~ stone_stairs[facing=north,half=top]
execute if entity @s[y_rotation=135..-135.01] run summon armor_stand ~0.5 ~0.25 ~0.5 {Tags: [tpExtractor,tpBeltS,tpBeltMove,tpNew],Invisible:1,Marker:1,NoGravity:1}

execute if entity @s[y_rotation=-135..-45] run setblock ~ ~ ~ stone_stairs[facing=east,half=top]
execute if entity @s[y_rotation=-135..-45] run summon armor_stand ~0.5 ~0.25 ~0.5 {Tags: [tpExtractor,tpBeltW,tpBeltMove,tpNew],Invisible:1,Marker:1,NoGravity:1,Rotation:[90f,0f]}

execute as @e[tag=tpExtractor,tag=tpNew] at @s run replaceitem entity @s armor.head minecraft:firework_rocket{CustomModelData:3390020}
execute as @e[tag=tpExtractor,tag=tpNew] at @s run tag @s remove tpNew