#######
# Compiled from .//functions/exmain.mcscript
# to .//functions/exmain.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set @s tpE 0
execute store result score @s tpE run data get block ^ ^ ^-1 Items[0].Count
execute if data block ^ ^ ^-1 Items[{Slot:0b,tag:{placeholder:1}}] run scoreboard players set @s tpE 0

execute as @s[scores={tpE=1..}] run tag @s add tpExActive
execute as @s[tag=tpExActive] positioned ^ ^ ^-1 if entity @e[tag=tpFilter,distance=..0.9] run tag @s add tpExFilter
execute as @s[tag=tpExFilter] if score @s tpE matches ..1 run tag @s remove tpExActive
execute as @s[tag=tpExFilter] run tag @s remove tpExFilter
execute as @s[tag=tpExActive] run summon item ^ ^-0.1 ^0.45 {Item:{id:"minecraft:stone",Count:1},Tags:[tpExNew]}
execute as @s[tag=tpExActive] as @e[tag=tpExNew,distance=..0.5] run data modify entity @s Item set from block ^ ^ ^-1 Items[0]
execute as @s[tag=tpExActive] as @e[tag=tpExNew,distance=..0.5] run data modify entity @s Item.Count set value 1
execute as @s[tag=tpExActive] run tag @e[tag=tpExNew,distance=..0.5] remove tpExNew
execute as @s[tag=tpExActive] run scoreboard players remove @s tpE 1
execute as @s[tag=tpExActive] store result block ^ ^ ^-1 Items[0].Count byte 1 run scoreboard players get @s tpE
execute as @s[tag=tpExActive] run tag @s remove tpExActive