#######
# Compiled from .//functions/main.mcscript
# to .//functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[tag=tpExtractor] at @s if block ~ ~ ~ air run summon minecraft:item ~ ~0.5 ~ {Item:{id:"minecraft:firework_rocket",Count:1,tag:{CustomModelData:3390020,isTekPack:1,HideFlags:6,display:{Name:"{\"text\":\"Extractor\",\"italic\":false,\"color\":\"gray\"}"},Fireworks:{}}}}
execute as @e[tag=tpExtractor] at @s if block ~ ~ ~ air run kill @e[type=item,distance=..0.8,nbt={Item:{id:"minecraft:stone_stairs"}}]
execute as @e[tag=tpExtractor] at @s if block ~ ~ ~ air run kill @s
execute as @e[tag=tpExtractor] at @s run scoreboard players add @s tpTimer 1
execute as @e[tag=tpExtractor] at @s run function tpextractor:powered
execute as @e[tag=tpExtractor] at @s if score @s tpTimer matches 30.. run function tpextractor:exmain
execute as @e[tag=tpExtractor] at @s if score @s tpTimer matches 30.. run scoreboard players reset @s tpTimer